/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: 'var(--card)',
        'card-foreground': 'var(--card-foreground)',
        popover: 'var(--popover)',
        'popover-foreground': 'var(--popover-foreground)',
        primary: 'var(--primary)',
        'primary-foreground': 'var(--primary-foreground)',
        secondary: 'var(--secondary)',
        'secondary-foreground': 'var(--secondary-foreground)',
        muted: 'var(--muted)',
        'muted-foreground': 'var(--muted-foreground)',
        accent: 'var(--accent)',
        'accent-foreground': 'var(--accent-foreground)',
        destructive: 'var(--destructive)',
        'destructive-foreground': 'var(--destructive-foreground)',
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        viao: {
          bg: 'var(--background)',
          bg2: 'var(--secondary)',
          panel: 'var(--card)',
          panelSoft: 'var(--secondary)',
          line: 'var(--border)',
          text: 'var(--foreground)',
          muted: 'var(--muted-foreground)',
          accent: 'var(--primary)',
          accent2: 'color-mix(in oklab, var(--primary) 88%, black)',
          accentLight: 'color-mix(in oklab, var(--primary) 12%, white)',
          accentRing: 'color-mix(in oklab, var(--primary) 25%, transparent)',
          success: '#34d399',
          warn: '#f59e0b',
          danger: '#ef4444',
        },
      },
      boxShadow: {
        viao: '0 1px 2px rgba(15, 23, 42, 0.04)',
        viaoLg: '0 10px 28px rgba(15, 23, 42, 0.06)',
      },
      backdropBlur: {
        viao: '16px',
      },
    },
  },
  plugins: [],
};
